service: lambda-url-shortener

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 128
  environment:
    MONGO_URI: ${env:MONGO_URI}

functions:
  getUrl:
    handler: handler.getUrl
    events:
      - http:
          path: url
          method: get
  createUrl:
    handler: handler.createUrl
    events:
      - http:
          path: url
          method: post
  getStats:
    handler: handler.getStats
    events:
      - http:
          path: url/stats
          method: get
  cleanUrls:
    handler: handler.cleanUrls
    events:
      - schedule:
        enabled: true
        rate: cron(0 12 ? * * *)

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

package:
  exclude:
    - '**/*.test.ts'
  include:
    src/**
